steps:
    # Step 1: Build the Docker image
    - name: 'gcr.io/cloud-builders/docker'
      args:
        - 'build'
        - '-t'
        - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cw-cicd-test/app:${_ENVIRONMENT}'
        - '-t'
        - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cw-cicd-test/app:$SHORT_SHA'
        - '.'
  
    # Step 2: Push to Artifact Registry
    - name: 'gcr.io/cloud-builders/docker'
      args:
        - 'push'
        - '--all-tags'
        - '${_REGION}-docker.pkg.dev/$PROJECT_ID/cw-cicd-test/app'
  
    # Step 3: Deploy to Cloud Run
    - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
      entrypoint: gcloud
      args:
        - 'run'
        - 'deploy'
        - 'cw-cicd-test-${_ENVIRONMENT}'
        - '--image=${_REGION}-docker.pkg.dev/$PROJECT_ID/cw-cicd-test/app:${_ENVIRONMENT}'
        - '--region=${_REGION}'
        - '--platform=managed'
        - '--allow-unauthenticated'
        - '--port=8000'
  
  substitutions:
    _ENVIRONMENT: 'staging'
    _REGION: 'europe-west2'
  
  options:
    logging: CLOUD_LOGGING_ONLY
    machineType: 'E2_HIGHCPU_8'
  
  timeout: '1200s'